'use client'

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowRight, Bean, Check, ChevronLeft, ChevronRight, Clock3, Coffee, MapPin, Menu, Minus, Moon, Package, Plus, Search, ShoppingBag, Star, Sunrise, X } from "lucide-react";

type Product = { id:number; name:string; price:number; origin:string; roast:string; tasting_notes:string; process:string; stock:number; roaster:string; featured:number };
type CartItem = Product & { quantity:number };
const fallback: Product[] = [
  [1,"Konga Sun Dried",22,"Ethiopia","Light","Blueberry · jasmine · cacao","Natural",7,"Morrow Coffee",1],
  [2,"La Palma Gesha",28,"Colombia","Light","Bergamot · peach · honey","Washed",5,"Altura Lab",1],
  [3,"Kerinci Valley",19,"Indonesia","Medium","Cedar · plum · brown sugar","Honey",12,"Common Ground",1],
  [4,"Nariño Reserve",21,"Colombia","Medium","Caramel · red apple · cocoa","Washed",3,"Fieldwork Roasters",1],
  [5,"Guji Moon",23,"Ethiopia","Light","Strawberry · hibiscus · vanilla","Natural",9,"Morrow Coffee",0],
  [6,"Sumatra Lintong",18,"Indonesia","Dark","Dark chocolate · clove · molasses","Wet hulled",14,"Common Ground",0],
  [7,"Huila Night Decaf",20,"Colombia","Medium","Toffee · orange · almond","Sugarcane decaf",8,"Altura Lab",0],
  [8,"Sidama Ardi",24,"Ethiopia","Light","Lemon · black tea · apricot","Washed",2,"Fieldwork Roasters",0],
  [9,"Java Ijen",19,"Indonesia","Dark","Tobacco · cocoa nib · spice","Natural",11,"Morrow Coffee",0],
].map(([id,name,price,origin,roast,tasting_notes,process,stock,roaster,featured])=>({id,name,price,origin,roast,tasting_notes,process,stock,roaster,featured} as Product));

function CoffeeArt({ roast="Light", index=0 }:{ roast?:string; index?:number }) {
  const tone=roast==="Dark"?"from-[#28130b] to-[#6a3820]":roast==="Medium"?"from-[#8d4b28] to-[#d69a65]":"from-[#d5a16e] to-[#f1d5b4]";
  return <div className={`relative h-64 overflow-hidden bg-gradient-to-br ${tone}`}><div className="absolute inset-0 paper-grain opacity-30"/><div className="absolute -right-10 -top-10 h-44 w-44 rounded-full border border-white/20"/><div className="absolute left-1/2 top-1/2 h-36 w-24 -translate-x-1/2 -translate-y-1/2 rounded-t-[3rem] rounded-b-xl bg-[#f8f0e6] shadow-2xl"><div className="mx-auto mt-8 flex h-20 w-16 flex-col items-center justify-center border border-[#5d321f]/30 text-center text-[9px] font-semibold uppercase tracking-[.18em] text-[#5d321f]"><Bean className="mb-2 h-5 w-5"/>Vault<br/>No. {String(index+1).padStart(2,"0")}</div></div></div>;
}

export default function Home(){
  const [products,setProducts]=useState(fallback),[open,setOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[cart,setCart]=useState<CartItem[]>([]);
  const [origin,setOrigin]=useState("All origins"),[roast,setRoast]=useState("All roasts"),[query,setQuery]=useState(""),[slide,setSlide]=useState(0);
  const [email,setEmail]=useState(""),[sending,setSending]=useState(false),[formState,setFormState]=useState<"idle"|"success"|"error">("idle");
  useEffect(()=>{fetch("/api/products").then(r=>r.ok?r.json():Promise.reject()).then(setProducts).catch(()=>undefined)},[]);
  useEffect(()=>{const t=setInterval(()=>setSlide(s=>(s+1)%3),5000);return()=>clearInterval(t)},[]);
  const visible=useMemo(()=>products.filter(p=>(origin==="All origins"||p.origin===origin)&&(roast==="All roasts"||p.roast===roast)&&`${p.name} ${p.tasting_notes} ${p.roaster}`.toLowerCase().includes(query.toLowerCase())),[products,origin,roast,query]);
  const count=cart.reduce((n,i)=>n+i.quantity,0),total=cart.reduce((n,i)=>n+i.price*i.quantity,0);
  function add(p:Product){setCart(c=>{const f=c.find(i=>i.id===p.id);return f?c.map(i=>i.id===p.id?{...i,quantity:Math.min(i.quantity+1,i.stock)}:i):[...c,{...p,quantity:1}]});setCartOpen(true)}
  function adjust(id:number,d:number){setCart(c=>c.map(i=>i.id===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0))}
  async function subscribe(e:FormEvent){e.preventDefault();setSending(true);setFormState("idle");try{const r=await fetch(`${process.env.NEXT_PUBLIC_CONSTRUCTOR_API}/v1/forms/${process.env.NEXT_PUBLIC_PROJECT_ID}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,interest:"CoffeeVault roast alerts"})});if(!r.ok)throw new Error();setFormState("success")}catch{setFormState("error")}finally{setSending(false)}}
  const links=[["Catalog","#catalog"],["Categories","#categories"],["Our story","#story"],["Membership","#membership"]];
  return <main className="overflow-hidden bg-cream text-espresso">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-white/15 bg-[#160b06]/90 text-white backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-[1440px] items-center justify-between px-5 lg:px-10"><a href="#top" className="font-serif text-xl">CoffeeVault<span className="text-copper">.</span></a><nav className="hidden gap-7 text-[12px] uppercase tracking-[.16em] lg:flex">{links.map(([l,h])=><a key={l} href={h} className="hover:text-copper">{l}</a>)}</nav><div className="flex items-center gap-2"><a href="#catalog" aria-label="Search catalog" className="p-2"><Search className="h-4 w-4"/></a><button aria-label="Open shopping bag" onClick={()=>setCartOpen(true)} className="relative p-2"><ShoppingBag className="h-4 w-4"/>{count>0&&<span className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-copper px-1 text-[9px]">{count}</span>}</button><button aria-label="Toggle menu" onClick={()=>setOpen(!open)} className="p-2 lg:hidden">{open?<X/>:<Menu/>}</button></div></div><div className={`absolute inset-x-0 top-18 border-b border-white/15 bg-[#160b06] px-6 py-7 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] lg:hidden ${open?"pointer-events-auto translate-y-0 opacity-100":"pointer-events-none -translate-y-4 opacity-0"}`}>{links.map(([l,h],i)=><a key={l} href={h} onClick={()=>setOpen(false)} style={{transitionDelay:open?`${i*60}ms`:'0ms'}} className="block border-b border-white/10 py-4 font-serif text-2xl transition-all duration-500">{l}</a>)}</div></header>

    <section id="top" className="relative flex min-h-[94vh] items-end bg-[#2b160d] px-5 pb-20 pt-32 text-white lg:px-10 lg:pb-24"><div className="absolute inset-0 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_68%_35%,#a85f2d_0,#472312_27%,#180c07_70%)]"/>{[...Array(15)].map((_,i)=><div key={i} className="bean-shape absolute h-14 w-10 bg-gradient-to-br from-[#9a4f26] to-[#32160b] shadow-2xl" style={{left:`${48+(i*13)%52}%`,top:`${9+(i*17)%70}%`,transform:`rotate(${i*39}deg) scale(${.7+(i%4)*.2})`}}><span className="absolute left-1/2 top-2 h-10 w-px -rotate-12 bg-[#d59a69]/40"/></div>)}<div className="absolute inset-0 bg-gradient-to-r from-[#160b06] via-[#160b06]/75 to-transparent"/><div className="absolute inset-0 paper-grain opacity-30"/></div><div className="relative z-10 mx-auto w-full max-w-[1440px]"><p className="mb-5 flex items-center gap-3 text-xs uppercase tracking-[.24em] text-[#e5b68e]"><span className="h-px w-8 bg-copper"/>Curated at origin · Roasted to order</p><h1 className="max-w-3xl font-serif text-[clamp(2.9rem,6vw,5.8rem)] leading-[.98] tracking-[-.045em]">Source exceptional coffee directly from micro roasters.</h1><p className="mt-7 max-w-xl text-base leading-7 text-[#e0cbb9] lg:text-lg">Freshly roasted within 48 hours of order. Curated single origins with full roaster profiles and tasting notes.</p><div className="mt-9 flex flex-wrap items-center gap-6"><a href="#catalog" className="inline-flex items-center gap-3 rounded-sm bg-[#f7eee5] px-6 py-4 text-sm font-semibold text-espresso">Explore our catalog <ArrowRight className="h-4 w-4"/></a><a href="#story" className="border-b border-copper pb-1 text-sm text-[#efbb93]">View our story</a></div></div><a href="#trust" aria-label="Scroll to trust highlights" className="absolute bottom-8 right-8 hidden items-center gap-3 text-[10px] uppercase tracking-[.2em] text-white/60 lg:flex">Discover <ArrowDown className="h-4 w-4 animate-bounce"/></a></section>

    <section id="trust" className="border-b border-[#d8c9b8] bg-paper"><div className="mx-auto grid max-w-[1440px] grid-cols-2 lg:grid-cols-4">{[[Star,"2,847","Five star reviews"],[Clock3,"14 day","Freshness guarantee"],[MapPin,"100%","Traceable origins"],[Bean,"37","Single origin coffees"]].map(([I,n,l],i)=>{const Icon=I as typeof Star;return <div key={l as string} className={`flex items-center gap-4 px-5 py-7 lg:px-10 ${i%2?'':'border-r'} border-[#d8c9b8] lg:border-r`}><Icon className="h-5 w-5 text-copper"/><div><div className="font-serif text-2xl">{n as string}</div><div className="text-[10px] uppercase tracking-[.16em] text-gold">{l as string}</div></div></div>})}</div></section>

    <section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><Title kicker="This week’s roast list" title="Featured coffees"/><div className="grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} index={i} add={add}/>)}</div></div></section>

    <section id="categories" className="bg-[#211109] px-5 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><Title kicker="Find your ritual" title="Browse by character" dark/><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{[[Sunrise,"Light roast","Floral and vivid"],[Coffee,"Medium roast","Sweet and balanced"],[Bean,"Dark roast","Deep and resonant"],[Moon,"Decaf","Quietly expressive"],[Package,"Bulk orders","Built for sharing"],[Coffee,"Brewing gear","Tools for clarity"]].map(([I,t,s],i)=>{const Icon=I as typeof Coffee;return <button key={t as string} onClick={()=>{if(i<3)setRoast((t as string).split(" ")[0]);document.getElementById("catalog")?.scrollIntoView()}} className={`group relative min-h-48 overflow-hidden border border-white/15 p-5 text-left hover:border-copper md:min-h-64 md:p-8 ${i===0?'md:col-span-2 bg-gradient-to-br from-[#7d4527] to-[#2a150b]':'bg-white/[.035]'}`}><Icon className="mb-12 h-7 w-7 text-[#d99a6d]"/><h3 className="font-serif text-2xl md:text-3xl">{t as string}</h3><p className="mt-2 text-xs uppercase tracking-[.14em] text-white/50">{s as string}</p><ArrowRight className="absolute bottom-6 right-6 h-5 w-5 text-copper"/></button>})}</div></div></section>

    <section id="catalog" className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="mb-10 lg:flex lg:items-end lg:justify-between"><Title kicker="The complete collection" title="Roast catalog"/><div className="flex flex-wrap gap-3"><label className="flex items-center gap-2 border-b border-espresso/30"><Search className="h-4 w-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasting notes" className="w-44 bg-transparent py-3 text-sm outline-none"/></label><select aria-label="Filter by origin" value={origin} onChange={e=>setOrigin(e.target.value)} className="border border-[#d8c9b8] bg-transparent px-3 py-3 text-sm">{["All origins","Ethiopia","Colombia","Indonesia"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by roast" value={roast} onChange={e=>setRoast(e.target.value)} className="border border-[#d8c9b8] bg-transparent px-3 py-3 text-sm">{["All roasts","Light","Medium","Dark"].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{visible.map((p,i)=><ProductCard key={p.id} product={p} index={i+4} add={add}/>)}</div>{!visible.length&&<p className="border-y py-16 text-center font-serif text-2xl">No coffees match those filters.</p>}</div></section>

    <section className="bg-paper px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="flex items-start justify-between"><Title kicker="Community favorites" title="Bestsellers"/><div className="flex gap-2"><button aria-label="Previous coffees" onClick={()=>setSlide(s=>(s+2)%3)} className="grid h-11 w-11 place-items-center border"><ChevronLeft/></button><button aria-label="Next coffees" onClick={()=>setSlide(s=>(s+1)%3)} className="grid h-11 w-11 place-items-center border"><ChevronRight/></button></div></div><div className="grid gap-5 md:grid-cols-3">{products.slice(slide*3,slide*3+3).map((p,i)=><div key={p.id} className="relative bg-cream"><span className="absolute right-0 top-0 z-10 bg-copper px-3 py-2 text-[10px] uppercase tracking-[.18em] text-white">Best seller</span><ProductCard product={p} index={slide*3+i} add={add}/></div>)}</div><div className="mt-8 flex justify-center gap-2">{[0,1,2].map(i=><button key={i} aria-label={`Show bestseller set ${i+1}`} onClick={()=>setSlide(i)} className={`h-1 ${slide===i?'w-10 bg-copper':'w-4 bg-espresso/20'}`}/>)}</div></div></section>

    <section id="story" className="relative overflow-hidden bg-[#b76e3e] px-5 py-24 lg:px-10 lg:py-36"><div className="absolute -right-16 -top-20 h-96 w-96 rounded-full border border-espresso/15"/><div className="relative mx-auto max-w-4xl text-center"><Bean className="mx-auto mb-8"/><p className="mb-6 text-xs uppercase tracking-[.24em]">Coffee without the mystery</p><h2 className="font-serif text-4xl leading-tight lg:text-7xl">Every bag begins with a name, a place, and a harvest.</h2><p className="mx-auto mt-8 max-w-2xl leading-8">We work with independent roasters who buy intentionally and share the details. You see the producer, process, elevation, roast date, and the people responsible for bringing each lot to life.</p><a href="#catalog" className="mt-9 inline-flex items-center gap-2 border-b border-espresso pb-1 text-sm font-semibold">Meet the coffees <ArrowRight className="h-4 w-4"/></a></div></section>

    <section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="text-center"><Title kicker="Notes from the brew table" title="Loved by careful drinkers"/></div><div className="grid border-y border-[#d8c9b8] md:grid-cols-3">{[["SC","I’ve tried more than 30 specialty roasters over five years. These Ethiopian naturals reminded me why I fell in love with coffee.","Sarah Chen","Home brewer · Seattle"],["MW","The roaster profiles are obsessively detailed. You feel connected to the actual farmer. That is rare.","Marcus Webb","Coffee blogger · Brew Community"],["JP","Consistently excellent. My morning ritual tastes expensive but costs less than my local café.","Dr. James Patterson","Coffee enthusiast · Boston"]].map(([a,q,n,r],i)=><article key={n} className={`py-10 md:p-10 ${i<2?'md:border-r md:border-[#d8c9b8]':''}`}><div className="mb-8 grid h-11 w-11 place-items-center rounded-full bg-paper text-xs font-bold text-copper">{a}</div><blockquote className="font-serif text-xl italic leading-8">“{q}”</blockquote><p className="mt-8 text-sm font-semibold">{n}</p><p className="mt-1 text-xs text-gold">{r}</p></article>)}</div></div></section>

    <section id="membership" className="bg-[#211109] px-5 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto max-w-[1240px]"><div className="text-center"><Title kicker="Membership" title="A better bag, every time" dark/></div><div className="grid items-center gap-4 md:grid-cols-3">{[{n:"Starter",p:"$14.99",f:["Single origin sourcing","Roast date guarantee","Standard shipping","Email tasting guide","Member discounts after three purchases"]},{n:"Enthusiast",p:"$18.99",pop:true,f:["Everything in Starter","Early limited release access","Free shipping on five bags","Quarterly tasting box","Direct roaster correspondence"]},{n:"Collector",p:"$24.99",f:["Everything in Enthusiast","Monthly rare micro lot","White glove fulfillment","Annual roaster visit opportunity","Dedicated chat concierge"]}].map(t=><article key={t.n} className={`relative border p-7 lg:p-9 ${t.pop?'border-copper bg-copper text-espresso md:py-14':'border-white/15 bg-white/[.03]'}`}>{t.pop&&<span className="absolute right-5 top-5 text-[9px] font-bold uppercase tracking-[.2em]">Most popular</span>}<p className="text-xs uppercase tracking-[.2em] opacity-70">{t.n}</p><div className="my-6 font-serif text-4xl">{t.p}<span className="font-sans text-xs opacity-60"> / bag</span></div><ul className="space-y-4">{t.f.map(x=><li key={x} className="flex gap-3 text-sm"><Check className="h-4 w-4 shrink-0"/>{x}</li>)}</ul><a href="#newsletter" className={`mt-8 block py-3 text-center text-xs font-semibold uppercase tracking-[.16em] ${t.pop?'bg-espresso text-white':'border border-white/30'}`}>Join {t.n}</a></article>)}</div></div></section>

    <section id="newsletter" className="border-b border-[#d8c9b8] bg-paper px-5 py-14 lg:px-10"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><p className="font-serif text-3xl">The first pour</p><p className="mt-2 text-sm text-gold">Limited releases, roast alerts, and practical tasting guides.</p></div>{formState==="success"?<p className="font-semibold text-[#42633b]">✓ Mensaje enviado — te contactaremos pronto</p>:<form onSubmit={subscribe} className="w-full max-w-lg"><div className="flex border-b border-espresso"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" className="min-w-0 flex-1 bg-transparent py-4 outline-none"/><button disabled={sending} className="flex items-center gap-2 px-3 text-sm font-semibold">{sending?"Enviando…":"Get roast alerts"}<ArrowRight className="h-4 w-4"/></button></div>{formState==="error"&&<p className="mt-2 text-sm text-red-700">We could not send your request. Please try again.</p>}</form>}</div></section>

    <section className="px-5 py-24 text-center lg:py-36"><p className="mb-5 text-xs uppercase tracking-[.24em] text-copper">Your next favorite coffee is here</p><h2 className="mx-auto max-w-4xl font-serif text-5xl leading-[1.05] lg:text-8xl">Brew something worth remembering.</h2><a href="#catalog" className="mt-9 inline-flex items-center gap-3 bg-espresso px-7 py-4 text-sm font-semibold text-white">Shop fresh roasts <ArrowRight className="h-4 w-4"/></a></section>

    <footer className="bg-[#160b06] px-5 pb-8 pt-16 text-white lg:px-10"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 border-b border-white/15 pb-14 md:grid-cols-4"><div className="md:col-span-2"><div className="font-serif text-3xl">CoffeeVault<span className="text-copper">.</span></div><p className="mt-5 max-w-sm text-sm leading-6 text-white/50">A curated shelf of traceable coffees from small, exacting roasters. Freshness is part of the flavor.</p></div><div><p className="mb-5 text-xs uppercase tracking-[.18em] text-copper">Explore</p>{links.map(([l,h])=><a key={l} href={h} className="mb-3 block text-sm text-white/70">{l}</a>)}</div><div><p className="mb-5 text-xs uppercase tracking-[.18em] text-copper">Service</p><a href="#trust" className="mb-3 block text-sm text-white/70">Freshness promise</a><a href="#newsletter" className="mb-3 block text-sm text-white/70">Roast alerts</a><button onClick={()=>setCartOpen(true)} className="block text-sm text-white/70">View shopping bag</button></div></div><div className="flex flex-col justify-between gap-3 pt-7 text-[10px] uppercase tracking-[.15em] text-white/35 sm:flex-row"><span>© 2026 CoffeeVault</span><span>Traceable coffee · Thoughtful roasting · Better mornings</span></div></div></footer>

    <div className={`fixed inset-0 z-50 transition ${cartOpen?'pointer-events-auto bg-black/50':'pointer-events-none bg-transparent'}`} onClick={()=>setCartOpen(false)}><aside onClick={e=>e.stopPropagation()} className={`absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-cream p-6 shadow-2xl transition-transform duration-500 ${cartOpen?'translate-x-0':'translate-x-full'}`}><div className="flex items-center justify-between border-b pb-5"><div><p className="font-serif text-2xl">Your bag</p><p className="text-xs text-gold">{count} coffees selected</p></div><button aria-label="Close shopping bag" onClick={()=>setCartOpen(false)}><X/></button></div><div className="flex-1 overflow-auto py-4">{!cart.length?<div className="grid h-full place-items-center text-center"><p className="font-serif text-xl">Your bag is ready for a remarkable coffee.</p></div>:cart.map(i=><div key={i.id} className="flex gap-4 border-b py-5"><div className="grid h-20 w-16 place-items-center bg-[#a75b32] text-white"><Bean/></div><div className="flex-1"><p className="font-serif">{i.name}</p><p className="text-xs text-gold">{i.origin} · {i.roast}</p><div className="mt-3 flex items-center gap-3"><button aria-label={`Remove one ${i.name}`} onClick={()=>adjust(i.id,-1)}><Minus className="h-3 w-3"/></button><span className="text-xs">{i.quantity}</span><button aria-label={`Add one ${i.name}`} onClick={()=>adjust(i.id,1)} disabled={i.quantity>=i.stock}><Plus className="h-3 w-3"/></button></div></div><span className="text-sm font-semibold">${i.price*i.quantity}</span></div>)}</div>{cart.length>0&&<div className="border-t pt-5"><div className="flex justify-between font-serif text-xl"><span>Subtotal</span><span>${total.toFixed(2)}</span></div><p className="mt-2 text-xs text-gold">Roasted this week. Shipping is calculated at checkout.</p><button onClick={()=>alert("Checkout is ready for secure payment connection.")} className="mt-5 w-full bg-espresso py-4 text-sm font-semibold text-white">Continue to secure checkout</button></div>}</aside></div>
  </main>
}

function Title({kicker,title,dark=false}:{kicker:string;title:string;dark?:boolean}){return <div className="mb-10"><p className={`mb-3 text-xs uppercase tracking-[.22em] ${dark?'text-[#d99a6d]':'text-copper'}`}>{kicker}</p><h2 className="font-serif text-4xl lg:text-6xl">{title}</h2></div>}
function ProductCard({product,index,add}:{product:Product;index:number;add:(p:Product)=>void}){return <article className="group"><div className="relative overflow-hidden"><CoffeeArt roast={product.roast} index={index}/><button onClick={()=>add(product)} aria-label={`Add ${product.name} to shopping bag`} className="absolute bottom-3 right-3 grid h-11 w-11 translate-y-16 place-items-center rounded-full bg-cream shadow-lg transition duration-300 group-hover:translate-y-0 focus:translate-y-0"><Plus className="h-5 w-5"/></button></div><div className="pt-5"><div className="flex justify-between text-[10px] uppercase tracking-[.16em] text-gold"><span>{product.origin} · {product.process}</span><span>{product.roast}</span></div><div className="mt-2 flex justify-between gap-3"><h3 className="font-serif text-xl">{product.name}</h3><span className="font-semibold text-copper">${Number(product.price).toFixed(2)}</span></div><p className="mt-2 text-sm text-gold">{product.tasting_notes}</p><div className="mt-4 flex justify-between border-t pt-3 text-xs"><span className={product.stock<5?'text-red-700':'text-gold'}>{product.stock<5?`Only ${product.stock} left`:`${product.stock} bags in stock`}</span><button onClick={()=>add(product)} className="font-semibold text-copper">Add to bag</button></div></div></article>}
